export enum AppErrorCodes {
  NOT_FOUND = "NOT_FOUND",
  MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS",
  MISSING_REQUIRED_PARAMETERS = "MISSING_REQUIRED_PARAMETERS",
  BLOCK_USER_FAILED = "BLOCK_USER_FAILED",
}
