export enum UserErrorCodes {
  EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED",
  ALIAS_ALREADY_USED = "ALIAS_ALREADY_USED",
  CANNOT_BLOCK_YOURSELF = "CANNOT_BLOCK_YOURSELF",
  USER_ALREADY_BLOCKED = "USER_ALREADY_BLOCKED",
  USER_IS_NOT_BLOCKED = "USER_IS_NOT_BLOCKED",
}
