export enum ErrorCodes {
  EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED",
  ALIAS_ALREADY_USED = "ALIAS_ALREADY_USED",
  INVALID_VALUE_OBJECT = "INVALID_VALUE_OBJECT",
  NOT_FOUND = "NOT_FOUND",
  ALREADY_LIKED = "ALREADY_LIKED",
  MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS",
  MISSING_REQUIRED_PARAMETERS = "MISSING_REQUIRED_PARAMETERS",
  INVALID_ENTITY_TIMESTAMPS = "INVALID_ENTITY_TIMESTAMPS",
  EXCEEDED_POST_IMAGE_LIMIT = "EXCEEDED_POST_IMAGE_LIMIT",
  INVALID_ENV_VARIABLE = "INVALID_ENV_VARIABLE",
  MISSING_ENV_VARIABLE = "MISSING_ENV_VARIABLE",
}
