export enum ErrorCodes {
  EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED",
  ALIAS_ALREADY_USED = "ALIAS_ALREADY_USED",
  INVALID_VALUE_OBJECT = "INVALID_VALUE_OBJECT",
  NOT_FOUND = "NOT_FOUND",
  ALREADY_LIKED = "ALREADY_LIKED",
  MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS",
  MISSING_REQUIRED_PARAMETERS = "MISSING_REQUIRED_PARAMETERS",
  INVALID_ENTITY_TIMESTAMPS = "INVALID_ENTITY_TIMESTAMPS",
  EXCEEDED_POST_IMAGE_LIMIT = "EXCEEDED_POST_IMAGE_LIMIT",
  INVALID_ENV_VARIABLE = "INVALID_ENV_VARIABLE",
  MISSING_ENV_VARIABLE = "MISSING_ENV_VARIABLE",
  CANNOT_BLOCK_YOURSELF = "CANNOT_BLOCK_YOURSELF",
  USER_ALREADY_BLOCKED = "USER_ALREADY_BLOCKED",
  BLOCK_USER_PERSISTENCE = "BLOCK_USER_PERSISTENCE",
  BLOCK_USER_FAILED = "BLOCK_USER_FAILED",
  USER_IS_NOT_BLOCKED = "USER_IS_NOT_BLOCKED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
}
